#!/bin/bash
# vim: ft=sh ts=2 sw=2 et ff=unix fenc=utf-8

# Print existence of system update or number of upgrade packages not installed
#
# ORIGIN: 2021-01-07 by hmr


_SYSTEM=$(uname -s | tr "[:upper:]" "[:lower:]")

case "${_SYSTEM}" in

  darwin )
    pkgs=0
    ;;

  linux )
    # Raspberrypi OS
    if [[ -e /etc/rpi-issue ]]; then
      pkgmgr="apt"
    # Ubuntu
    elif [[ -e /etc/ubuntu-advantage ]]; then
      pkgmgr="apt"
    # CentOS
    # Fedora
    # RedHat
    # Debian
    # elif
    fi

    case "${pkgmgr}" in
      apt )
        pkgs=$(LANG=C apt list --upgradable 2>/dev/null | grep upgradable | wc -l)
        ;;

      yum )
        ;;

    esac
    ;;
esac

if [ ${pkgs} -ne 0 ]; then
  echo "#[bg=red,fg=white] ${pkgs}! "
fi

