#!/bin/bash
# vim: ft=sh ts=2 sw=2 et ff=unix fenc=utf-8

# part of os-stats-tools
# print_update
#   Print number of unapplied updated packages.
#
# ORIGIN: 2022-12-14 by hmr

set -eu

trap 'exit 255' HUP QUIT TERM
trap 'echo SIGINT caught; exit 254' 2
trap 'echo SIGUSR1 caught; exit 253' USR1

APT_AVAILABLE="/var/lib/update-notifier/updates-available"
if [[ -e ${APT_AVAILABLE} ]]; then
  PKGS=($(grep -Eo "[[:digit:]]+" "${APT_AVAILABLE}"))
  [[ ${PKGS[0]:-0} = 0 ]] && exit
  if [[ ${PKGS[1]:-0} = 0 ]]; then
    TMP_COLOR="#[fg=color102,bg=color226]"
  else
    TMP_COLOR="#[fg=colour255,bg=red]"
  fi
  echo "$TMP_COLOR U:${PKGS[0]:-0}/S:${PKGS[1]:-0} "
fi
unset APT_AVAILABLE TMP_COLOR PKGS

