#!/usr/bin/env -S nice -n 19 /bin/sh
# vim: ft=sh ts=2 sw=2 et ff=unix fenc=utf-8

# part of os-stats-tools
# print_ipaddr
#   Print (one of) ip address(es) of this device.
#
# ORIGIN: 2020-12-18 by hmr


set -eu

trap 'exit 255' HUP QUIT TERM
trap 'echo SIGINT caught; exit 254' 2
trap 'echo SIGUSR1 caught; exit 253' USR1

_SYSTEM=$(uname -s | tr '[:upper:]' '[:lower:]')

case "${_SYSTEM}" in

    "darwin" )
        _NETIF=$(route -n get 0.0.0.0 2>/dev/null | awk '/interface: / {print $2}')
        /usr/sbin/ipconfig getifaddr "${_NETIF}"
        # _DEFGW=$(netstat -nr -f inet | grep default | awk '{print $2}') # Get the default gw
        # traceroute -nv ${_DEFGW} 2>&1 | tail -n 1 | awk '{print $6}'
        ;;

    "linux" )
        /bin/ip route | grep -E -v "default|docker" | head -n 1 | cut -d" " -f 9
        # ip route | grep "default" | cut -d" " -f9
        # another way
        # ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'
        ;;
esac

