#!/bin/sh
# vim: ft=sh ts=2 sw=2 et ff=unix fenc=utf-8

_SYSTEM=$(uname -s | tr "[A-Z]" "[a-z]")

case "${_SYSTEM}" in

    "darwin" )
        sysctl vm.loadavg | cut -d " " -f 3-5
        ;;

    "linux" )
        cat /proc/loadavg | cut -d" " -f1-3
        ;;

esac

