#!/bin/sh
# vim: ft=sh ts=2 sw=2 et ff=unix fenc=utf-8

# part of os-stats-tools
# print_temp
#   Print system temperature.
#
# ORIGIN: 2020-12-23 by hmr


set -eu

trap 'exit 255' HUP QUIT TERM
trap 'echo SIGINT caught; exit 254' 2
trap 'echo SIGUSR1 caught; exit 253' USR1

_SYSTEM=$(uname -s | tr "[A-Z]" "[a-z]")
_ARCH=$(uname -m | tr "[A-Z]" "[a-z]")


case "${_SYSTEM}" in

    "darwin" )
        # I don't know how to obtain temperature information from macOS...
        ;;

    "linux" )
        case "${_ARCH}" in
            "aarch64" )
                grep -i "raspberry" /proc/cpuinfo > /dev/null
                if [ $? -eq 0 ]; then
                    vcgencmd measure_temp | cut -c 6,7
                fi
                ;;

            "x86_64" )
                ;;
            "i386" )
                ;;
        esac
        ;;
esac

